all:
	cd deque && $(MAKE)
	cd list && $(MAKE)
	cd map && $(MAKE)
	cd pair && $(MAKE)
	cd string && $(MAKE)
	cd tuple && $(MAKE)
	cd unordered_map && $(MAKE)
	cd unordered_multiset && $(MAKE)
	cd unordered_set && $(MAKE)
	cd vector && $(MAKE)

clean:
	cd deque && $(MAKE) clean
	cd list && $(MAKE) clean
	cd map && $(MAKE) clean
	cd pair && $(MAKE) clean
	cd string && $(MAKE) clean
	cd tuple && $(MAKE) clean
	cd unordered_map && $(MAKE) clean
	cd unordered_multiset && $(MAKE) clean
	cd unordered_set && $(MAKE) clean
	cd vector && $(MAKE) clean
